defaults:
    # build command options
    build:
        # version name for hockey app
        app_version_name: 1.0.0
        # dir to gradle config
        gradle_file: app/build.gradle
        # root dir for android project
        root_dir: /path/to/project
        # gradlew execution command
        assemble: "clean assembleDebug"
    # release command options
    release: 
        # 0 - Do not notify
        should_notify: 0
        # status:
        # 2 - mr worldwide
        available_for_download: 2
        # 0 - Textile, 1 - Markdown
        notes_type: 1
        # release notes plain text file
        release_notes_path: /path/to/release_notes.txt
        # found in https://rink.hockeyapp.net/manage/auth_tokens
        user_app_token: 
        # app id from hockey app
        app_id: hockeyAppId
        # apk binary build path
        apk_path: /path/to/app.apk
release_build_type:
    # overrides defaults
    build:
        assemble: assembleRelease
    release:
        app_id: releaseHockeyAppId
        apk_path: /path/to/app-release.apk
